#! /bin/bash

# Copyright 2023 Software-Engineering-as-Code
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

OPERATION="Apply"
CHECK_OPT_BLACK=""
CHECK_OPT_ISORT=""

if [ "$#" -ge 1 ] && [ "$1" == "--check-only" ]; then
    OPERATION="Lint"
    CHECK_OPT_BLACK="--check"
    CHECK_OPT_ISORT="--check"
fi

ROOT_DIR=$(dirname $(dirname ${BASH_SOURCE}))

echo "################################################################################"
echo "### ${OPERATION} code quality with: black"
echo "################################################################################"
black ${ROOT_DIR} ${CHECK_OPT_BLACK}

echo -e "\n\n################################################################################"
echo "### ${OPERATION} code quality with: isort"
echo "################################################################################"
isort ${ROOT_DIR} ${CHECK_OPT_ISORT}

echo -e "\n\n################################################################################"
echo "### ${OPERATION} code quality with: mypy"
echo "################################################################################"
mypy ${ROOT_DIR}

#echo -e "\n\n################################################################################"
#echo "### ${OPERATION} code quality with: flake8"
#echo "################################################################################"
#flake8 ${ROOT_DIR}
