#! /bin/bash

# Copyright 2023 Software-Engineering-as-Code
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ROOT_DIR=$(dirname $(dirname ${BASH_SOURCE}))
VENV_DIR="${ROOT_DIR}/venv"

echo "Creating Python virtual environment in: ${VENV_DIR}"
python3 -m venv ${VENV_DIR}

echo "Installing package in editable mode: swe_as_code"
pip install -e ${ROOT_DIR}[test,lint]